name: Build open-vm-tools for Multiple Linux Distributions

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-20.04
          - ubuntu-22.04
          - centos-7
          - centos-8
          - rockylinux-8
          - rockylinux-9
          - almalinux-9
          - debian-10
          - debian-11

    container:
      image: ${{ matrix.distro == 'ubuntu-20.04' && 'ubuntu:20.04' || matrix.distro == 'ubuntu-22.04' && 'ubuntu:22.04' || matrix.distro == 'centos-7' && 'centos:7' || matrix.distro == 'centos-8' && 'centos:8' || matrix.distro == 'rockylinux-8' && 'rockylinux:8' || matrix.distro == 'rockylinux-9' && 'rockylinux:9' || matrix.distro == 'almalinux-9' && 'almalinux:9' || matrix.distro == 'debian-10' && 'debian:10' || matrix.distro == 'debian-11' && 'debian:11' }}

    steps:
    - name: Configure sources and install dependencies (Ubuntu 20.04)
      if: matrix.distro == 'ubuntu-20.04'
      run: |
        export DEBIAN_FRONTEND=noninteractive
        # 换国内源
        cat > /etc/apt/sources.list << 'EOF'
        deb https://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse
        deb https://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse
        deb https://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse
        deb https://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
        EOF
        
        apt-get update
        apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libgtkmm-3.0-dev \
          libpam0g-dev \
          libssl-dev \
          libxss1-dev \
          libicu-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxtst-dev \
          libmspack-dev \
          libudev-dev \
          libdrm-dev \
          libxcomposite-dev \
          libfuse-dev \
          libtirpc-dev \
          git \
          cmake

    - name: Configure sources and install dependencies (Ubuntu 22.04)
      if: matrix.distro == 'ubuntu-22.04'
      run: |
        export DEBIAN_FRONTEND=noninteractive
        # 换国内源
        cat > /etc/apt/sources.list << 'EOF'
        deb https://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse
        deb https://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse
        deb https://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse
        deb https://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse
        EOF
        
        apt-get update
        apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libgtkmm-3.0-dev \
          libpam0g-dev \
          libssl-dev \
          libxss1-dev \
          libicu-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxtst-dev \
          libmspack-dev \
          libudev-dev \
          libdrm-dev \
          libxcomposite-dev \
          libfuse3-dev \
          libtirpc-dev \
          git \
          cmake

    - name: Configure sources and install dependencies (Debian 10)
      if: matrix.distro == 'debian-10'
      run: |
        export DEBIAN_FRONTEND=noninteractive
        # 换国内源
        cat > /etc/apt/sources.list << 'EOF'
        deb https://mirrors.aliyun.com/debian/ buster main contrib non-free
        deb https://mirrors.aliyun.com/debian/ buster-updates main contrib non-free
        deb https://mirrors.aliyun.com/debian-security/ buster/updates main contrib non-free
        EOF
        
        apt-get update
        apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libgtkmm-3.0-dev \
          libpam0g-dev \
          libssl-dev \
          libxss1-dev \
          libicu-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxtst-dev \
          libmspack-dev \
          libudev-dev \
          libdrm-dev \
          libxcomposite-dev \
          libfuse-dev \
          libtirpc-dev \
          git \
          cmake

    - name: Configure sources and install dependencies (Debian 11)
      if: matrix.distro == 'debian-11'
      run: |
        export DEBIAN_FRONTEND=noninteractive
        # 换国内源
        cat > /etc/apt/sources.list << 'EOF'
        deb https://mirrors.aliyun.com/debian/ bullseye main contrib non-free
        deb https://mirrors.aliyun.com/debian/ bullseye-updates main contrib non-free
        deb https://mirrors.aliyun.com/debian-security/ bullseye-security main contrib non-free
        EOF
        
        apt-get update
        apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libgtkmm-3.0-dev \
          libpam0g-dev \
          libssl-dev \
          libxss1-dev \
          libicu-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxtst-dev \
          libmspack-dev \
          libudev-dev \
          libdrm-dev \
          libxcomposite-dev \
          libfuse3-dev \
          libtirpc-dev \
          git \
          cmake

    - name: Configure sources and install dependencies (CentOS 7)
      if: matrix.distro == 'centos-7'
      run: |
        # 换阿里云源
        curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
        yum clean all
        yum makecache
        
        # 安装EPEL源
        yum install -y epel-release
        
        yum groupinstall -y 'Development Tools'
        yum install -y \
          autoconf \
          automake \
          libtool \
          pkgconfig \
          glib2-devel \
          gtk3-devel \
          gtkmm30-devel \
          pam-devel \
          openssl-devel \
          libXScrnSaver-devel \
          libicu-devel \
          libXinerama-devel \
          libXrandr-devel \
          libXcursor-devel \
          libXtst-devel \
          libmspack-devel \
          systemd-devel \
          libdrm-devel \
          libXcomposite-devel \
          fuse-devel \
          libtirpc-devel \
          git \
          cmake3
        
        # 创建cmake软链接
        ln -sf /usr/bin/cmake3 /usr/bin/cmake

    - name: Configure sources and install dependencies (CentOS 8)
      if: matrix.distro == 'centos-8'
      run: |
        # 修复CentOS 8的源（使用vault镜像）
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        
        # 换阿里云源
        curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-vault-8.5.2111.repo
        yum clean all
        yum makecache
        
        # 安装PowerTools和EPEL
        yum install -y epel-release
        yum config-manager --set-enabled powertools
        
        yum groupinstall -y 'Development Tools'
        yum install -y \
          autoconf \
          automake \
          libtool \
          pkgconfig \
          glib2-devel \
          gtk3-devel \
          gtkmm30-devel \
          pam-devel \
          openssl-devel \
          libXScrnSaver-devel \
          libicu-devel \
          libXinerama-devel \
          libXrandr-devel \
          libXcursor-devel \
          libXtst-devel \
          libmspack-devel \
          systemd-devel \
          libdrm-devel \
          libXcomposite-devel \
          fuse3-devel \
          libtirpc-devel \
          git \
          cmake

    - name: Configure sources and install dependencies (Rocky Linux 8)
      if: matrix.distro == 'rockylinux-8'
      run: |
        # 换阿里云源
        sed -e 's|^mirrorlist=|#mirrorlist=|g' \
            -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirrors.aliyun.com/rockylinux|g' \
            -i.bak \
            /etc/yum.repos.d/Rocky-*.repo
        
        yum clean all
        yum makecache
        
        # 启用PowerTools和EPEL
        yum install -y epel-release
        yum config-manager --set-enabled powertools
        
        yum groupinstall -y 'Development Tools'
        yum install -y \
          autoconf \
          automake \
          libtool \
          pkgconfig \
          glib2-devel \
          gtk3-devel \
          gtkmm30-devel \
          pam-devel \
          openssl-devel \
          libXScrnSaver-devel \
          libicu-devel \
          libXinerama-devel \
          libXrandr-devel \
          libXcursor-devel \
          libXtst-devel \
          libmspack-devel \
          systemd-devel \
          libdrm-devel \
          libXcomposite-devel \
          fuse3-devel \
          libtirpc-devel \
          git \
          cmake

    - name: Configure sources and install dependencies (Rocky Linux 9)
      if: matrix.distro == 'rockylinux-9'
      run: |
        # 换阿里云源
        sed -e 's|^mirrorlist=|#mirrorlist=|g' \
            -e 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=https://mirrors.aliyun.com/rockylinux|g' \
            -i.bak \
            /etc/yum.repos.d/rocky*.repo
        
        yum clean all
        yum makecache
        
        # 启用CRB和EPEL
        yum install -y epel-release
        yum config-manager --set-enabled crb
        
        yum groupinstall -y 'Development Tools'
        yum install -y \
          autoconf \
          automake \
          libtool \
          pkgconfig \
          glib2-devel \
          gtk3-devel \
          gtkmm30-devel \
          pam-devel \
          openssl-devel \
          libXScrnSaver-devel \
          libicu-devel \
          libXinerama-devel \
          libXrandr-devel \
          libXcursor-devel \
          libXtst-devel \
          libmspack-devel \
          systemd-devel \
          libdrm-devel \
          libXcomposite-devel \
          fuse3-devel \
          libtirpc-devel \
          git \
          cmake

    - name: Configure sources and install dependencies (AlmaLinux 9)
      if: matrix.distro == 'almalinux-9'
      run: |
        # 换阿里云源
        sed -e 's|^mirrorlist=|#mirrorlist=|g' \
            -e 's|^# baseurl=https://repo.almalinux.org/almalinux|baseurl=https://mirrors.aliyun.com/almalinux|g' \
            -i.bak \
            /etc/yum.repos.d/almalinux*.repo
        
        yum clean all
        yum makecache
        
        # 启用CRB和EPEL
        yum install -y epel-release
        yum config-manager --set-enabled crb
        
        yum groupinstall -y 'Development Tools'
        yum install -y \
          autoconf \
          automake \
          libtool \
          pkgconfig \
          glib2-devel \
          gtk3-devel \
          gtkmm30-devel \
          pam-devel \
          openssl-devel \
          libXScrnSaver-devel \
          libicu-devel \
          libXinerama-devel \
          libXrandr-devel \
          libXcursor-devel \
          libXtst-devel \
          libmspack-devel \
          systemd-devel \
          libdrm-devel \
          libXcomposite-devel \
          fuse3-devel \
          libtirpc-devel \
          git \
          cmake

    - name: Checkout open-vm-tools source
      uses: actions/checkout@v4
      with:
        repository: vmware/open-vm-tools
        path: open-vm-tools
        fetch-depth: 0

    - name: Get latest version tag
      working-directory: open-vm-tools
      run: |
        # 获取最新的tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "master")
        echo "Latest tag: $LATEST_TAG"
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
        
        # 切换到最新tag或保持在master
        if [ "$LATEST_TAG" != "master" ]; then
          git checkout $LATEST_TAG
        fi

    - name: Build open-vm-tools
      working-directory: open-vm-tools/open-vm-tools
      run: |
        # 生成配置脚本
        autoreconf -fiv
        
        # 设置环境变量
        export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig"
        
        # 配置构建选项
        ./configure \
          --prefix=/usr \
          --sysconfdir=/etc \
          --localstatedir=/var \
          --libdir=/usr/lib64 \
          --enable-deploypkg \
          --enable-servicediscovery \
          --disable-tests \
          --without-xerces \
          --without-icu \
          --without-x \
          --without-gtk2 \
          --without-gtkmm \
          --without-kernel-modules \
          --with-fuse=yes
        
        # 编译
        make -j$(nproc)
        
        # 创建安装目录
        make DESTDIR=$PWD/install install

    - name: Create archive
      working-directory: open-vm-tools/open-vm-tools
      run: |
        # 获取版本信息
        VERSION=${LATEST_TAG:-"unknown"}
        echo "Building version: $VERSION for ${{ matrix.distro }}"
        
        # 创建包含版本信息的压缩包
        tar -czf "open-vm-tools-${VERSION}-${{ matrix.distro }}.tar.gz" -C install .

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: open-vm-tools-${{ env.LATEST_TAG }}-${{ matrix.distro }}
        path: open-vm-tools/open-vm-tools/open-vm-tools-*.tar.gz
        retention-days: 30

  # 创建发布包（可选）
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
